### ISSUE TITLE
Arabic translation

### ISSUE THREAD

**Issue by vbresan** [vbresan/HealthyBatteryCharging#11]
@islam2hamy Thank you for providing the Arabic translation of the app string resources! Since Arabic is read from right to left, the app layout needs to be oriented accordingly. I will use this channel to provide you with intermediate screenshots (before the official app release) so you can verify the alignment.

**Comment by islam2hamy** [comment]
Hello @vbresan ,
Ok

**Comment by vbresan** [comment]
@islam2hamy Please correct me if I am wrong, I believe this looks OK. Right? Though I just figured out that I need to flip the button effects and icon orientation too.


![Screenshot_20240623_100038](https://github.com/vbresan/HealthyBatteryCharging/assets/288855/f42fba81-c75c-4825-a165-b5aa81f5988d)

**Comment by islam2hamy** [comment]
@vbresan Yes it is ok

**Comment by vbresan** [comment]
@islam2hamy Awesome! Waiting for the remaining string resource to be translated before publishing the new release.

**Comment by islam2hamy** [comment]
@vbresan Done

**Comment by vbresan** [comment]
@islam2hamy Thank you!
