### ISSUE TITLE
gradle wrapper JAR missing

### ISSUE THREAD

**Issue by IzzySoft** [vbresan/HealthyBatteryCharging#24]
Could you please add the proper gradle wrapper JAR next to the `/gradle/wrapper/gradle-wrapper.properties` file? Thanks a lot!

**Comment by vbresan** [comment]
Done.

**Comment by IzzySoft** [comment]
Wonderful, thanks!

**Comment by IzzySoft** [comment]
PS, for some background: [Reproducible Builds, special client support and more at IzzyOnDroid](https://android.izzysoft.de/articles/named/iod-rbs-mirrors-clients) – and yes, your app successfully made it into the family of [Reproducible Builds](https://reproducible-builds.org/) :partying_face:

**Comment by IzzySoft** [comment]
Umpf. Now the JAR is there, but where's the `gradlew` start script for it, which usually resides in the project root? Without that, we still need to update each RB run manually. So could you please check and add that as well? Thanks in advance!

**Comment by vbresan** [comment]
@IzzySoft Added.

**Comment by IzzySoft** [comment]
Thanks a lot! Looking forward to the next release then to perform the (last) manual update to the recipe then :smile:
