### ISSUE TITLE
Doesn't work.

### ISSUE THREAD

**Issue by HarriBuh** [vbresan/HealthyBatteryCharging#31]
Google Pixel 7
Android 14

What I did to make your app work:
- Excluded it from any battery saving measures by changing its setting from "optimised" to "unrestricted"

I did not get any notifications.

**Comment by vbresan** [comment]
Are you getting notifications while the app is active in foreground?

**Comment by vbresan** [comment]
Could you please add a screenshot of the app's notification permission settings? You can access them by following the instructions in this short video: [Healthy Battery Charging for Android - Notification Permission Settings](https://youtube.com/shorts/LB9x0V_DXYw)
